### ISSUE TITLE
Should `system_dependencies` allow self referencing?

### ISSUE THREAD

**Issue by allisonking** [IABTechLab/fideslang#91]
### Is your feature request related to a specific problem?

Systems can send data to themselves, so is it useful to be able to list themselves as `system_dependencies`? Right now it is not possible. `system_dependencies` is deprecated, but `egress` and `ingress` are replacing it and _do_ allow self referencing. Making this issue as a place to discuss the pros/cons

### Additional context

Related to https://github.com/ethyca/fidesctl-plus/issues/193

**Comment by PSalant726** [comment]
It's very unlikely that any changes will be made to the `system_dependencies` implementation, other than to remove the field in a future version of fideslang (see #86).

Separately, whether or not self-referencing should be _displayed_ in a visual datamap is unrelated to the implementation detail of whether or not self-referencing should be allowed in `egress` and `ingress` `DataFlow`s. The `egress` and `ingress` fields are intentionally permissive, so any limiting of displayed data should be discussed as part of a front-end-only change, or it may be worth discussing that as part of a design discussion.

I'm closing this issue because no code changes will come out it.
